version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      # Spring Boot automatically uses these for DataSource config
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/users_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      # Optional: Controls Hibernate schema generation (use 'validate' or 'none' in prod)
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db # Ensures db starts before user-service

  # ... other services like product-catalog-service ...

  db: # PostgreSQL service definition
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data
    ports:
      - "5433:5432" # Optional: Expose DB port to host for direct access/debugging

volumes:
  postgres_data: # Define the named volume for persistence